// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Generated by cue.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { InnerTableQuery } from "./InnerTableQuery";
import {
  InnerTableQueryFromJSON,
  InnerTableQueryFromJSONTyped,
  InnerTableQueryToJSON,
  InnerTableQueryToJSONTyped,
} from "./InnerTableQuery";

/**
 *
 * @export
 * @interface InnerTableQueryChildInformation
 */
export interface InnerTableQueryChildInformation {
  /**
   *
   * @type {number}
   * @memberof InnerTableQueryChildInformation
   */
  rule: number;
  /**
   *
   * @type {number}
   * @memberof InnerTableQueryChildInformation
   */
  headIndex: number;
  /**
   *
   * @type {Array<InnerTableQuery>}
   * @memberof InnerTableQueryChildInformation
   */
  children: Array<InnerTableQuery>;
}

/**
 * Check if a given object implements the InnerTableQueryChildInformation interface.
 */
export function instanceOfInnerTableQueryChildInformation(
  value: object,
): value is InnerTableQueryChildInformation {
  if (!("rule" in value) || value["rule"] === undefined) return false;
  if (!("headIndex" in value) || value["headIndex"] === undefined) return false;
  if (!("children" in value) || value["children"] === undefined) return false;
  return true;
}

export function InnerTableQueryChildInformationFromJSON(
  json: any,
): InnerTableQueryChildInformation {
  return InnerTableQueryChildInformationFromJSONTyped(json, false);
}

export function InnerTableQueryChildInformationFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): InnerTableQueryChildInformation {
  if (json == null) {
    return json;
  }
  return {
    rule: json["rule"],
    headIndex: json["headIndex"],
    children: (json["children"] as Array<any>).map(InnerTableQueryFromJSON),
  };
}

export function InnerTableQueryChildInformationToJSON(
  json: any,
): InnerTableQueryChildInformation {
  return InnerTableQueryChildInformationToJSONTyped(json, false);
}

export function InnerTableQueryChildInformationToJSONTyped(
  value?: InnerTableQueryChildInformation | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    rule: value["rule"],
    headIndex: value["headIndex"],
    children: (value["children"] as Array<any>).map(InnerTableQueryToJSON),
  };
}
