// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Generated by cue.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface TableResponseBaseTableEntriesPagination
 */
export interface TableResponseBaseTableEntriesPagination {
  /**
   *
   * @type {number}
   * @memberof TableResponseBaseTableEntriesPagination
   */
  start: number;
  /**
   * count not required since this is the length of the array
   * @type {boolean}
   * @memberof TableResponseBaseTableEntriesPagination
   */
  moreEntriesExist: boolean;
}

/**
 * Check if a given object implements the TableResponseBaseTableEntriesPagination interface.
 */
export function instanceOfTableResponseBaseTableEntriesPagination(
  value: object,
): value is TableResponseBaseTableEntriesPagination {
  if (!("start" in value) || value["start"] === undefined) return false;
  if (!("moreEntriesExist" in value) || value["moreEntriesExist"] === undefined)
    return false;
  return true;
}

export function TableResponseBaseTableEntriesPaginationFromJSON(
  json: any,
): TableResponseBaseTableEntriesPagination {
  return TableResponseBaseTableEntriesPaginationFromJSONTyped(json, false);
}

export function TableResponseBaseTableEntriesPaginationFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TableResponseBaseTableEntriesPagination {
  if (json == null) {
    return json;
  }
  return {
    start: json["start"],
    moreEntriesExist: json["moreEntriesExist"],
  };
}

export function TableResponseBaseTableEntriesPaginationToJSON(
  json: any,
): TableResponseBaseTableEntriesPagination {
  return TableResponseBaseTableEntriesPaginationToJSONTyped(json, false);
}

export function TableResponseBaseTableEntriesPaginationToJSONTyped(
  value?: TableResponseBaseTableEntriesPagination | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    start: value["start"],
    moreEntriesExist: value["moreEntriesExist"],
  };
}
