// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Generated by cue.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface TableQueryBaseTableEntriesPagination
 */
export interface TableQueryBaseTableEntriesPagination {
  /**
   *
   * @type {number}
   * @memberof TableQueryBaseTableEntriesPagination
   */
  start: number;
  /**
   *
   * @type {number}
   * @memberof TableQueryBaseTableEntriesPagination
   */
  count: number;
}

/**
 * Check if a given object implements the TableQueryBaseTableEntriesPagination interface.
 */
export function instanceOfTableQueryBaseTableEntriesPagination(
  value: object,
): value is TableQueryBaseTableEntriesPagination {
  if (!("start" in value) || value["start"] === undefined) return false;
  if (!("count" in value) || value["count"] === undefined) return false;
  return true;
}

export function TableQueryBaseTableEntriesPaginationFromJSON(
  json: any,
): TableQueryBaseTableEntriesPagination {
  return TableQueryBaseTableEntriesPaginationFromJSONTyped(json, false);
}

export function TableQueryBaseTableEntriesPaginationFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TableQueryBaseTableEntriesPagination {
  if (json == null) {
    return json;
  }
  return {
    start: json["start"],
    count: json["count"],
  };
}

export function TableQueryBaseTableEntriesPaginationToJSON(
  json: any,
): TableQueryBaseTableEntriesPagination {
  return TableQueryBaseTableEntriesPaginationToJSONTyped(json, false);
}

export function TableQueryBaseTableEntriesPaginationToJSONTyped(
  value?: TableQueryBaseTableEntriesPagination | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    start: value["start"],
    count: value["count"],
  };
}
