// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Generated by cue.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface TableResponseBaseMetaInformation
 */
export interface TableResponseBaseMetaInformation {
  /**
   *
   * @type {number}
   * @memberof TableResponseBaseMetaInformation
   */
  executionTime: number;
}

/**
 * Check if a given object implements the TableResponseBaseMetaInformation interface.
 */
export function instanceOfTableResponseBaseMetaInformation(
  value: object,
): value is TableResponseBaseMetaInformation {
  if (!("executionTime" in value) || value["executionTime"] === undefined)
    return false;
  return true;
}

export function TableResponseBaseMetaInformationFromJSON(
  json: any,
): TableResponseBaseMetaInformation {
  return TableResponseBaseMetaInformationFromJSONTyped(json, false);
}

export function TableResponseBaseMetaInformationFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TableResponseBaseMetaInformation {
  if (json == null) {
    return json;
  }
  return {
    executionTime: json["executionTime"],
  };
}

export function TableResponseBaseMetaInformationToJSON(
  json: any,
): TableResponseBaseMetaInformation {
  return TableResponseBaseMetaInformationToJSONTyped(json, false);
}

export function TableResponseBaseMetaInformationToJSONTyped(
  value?: TableResponseBaseMetaInformation | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    executionTime: value["executionTime"],
  };
}
