// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Generated by cue.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { TableQueryBaseTableEntries } from "./TableQueryBaseTableEntries";
import {
  TableQueryBaseTableEntriesFromJSON,
  TableQueryBaseTableEntriesFromJSONTyped,
  TableQueryBaseTableEntriesToJSON,
  TableQueryBaseTableEntriesToJSONTyped,
} from "./TableQueryBaseTableEntries";

/**
 *
 * @export
 * @interface TableQueryBase
 */
export interface TableQueryBase {
  /**
   *
   * @type {TableQueryBaseTableEntries}
   * @memberof TableQueryBase
   */
  tableEntries?: TableQueryBaseTableEntries;
}

/**
 * Check if a given object implements the TableQueryBase interface.
 */
export function instanceOfTableQueryBase(
  value: object,
): value is TableQueryBase {
  return true;
}

export function TableQueryBaseFromJSON(json: any): TableQueryBase {
  return TableQueryBaseFromJSONTyped(json, false);
}

export function TableQueryBaseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TableQueryBase {
  if (json == null) {
    return json;
  }
  return {
    tableEntries:
      json["tableEntries"] == null
        ? undefined
        : TableQueryBaseTableEntriesFromJSON(json["tableEntries"]),
  };
}

export function TableQueryBaseToJSON(json: any): TableQueryBase {
  return TableQueryBaseToJSONTyped(json, false);
}

export function TableQueryBaseToJSONTyped(
  value?: TableQueryBase | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    tableEntries: TableQueryBaseTableEntriesToJSON(value["tableEntries"]),
  };
}
