// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Generated by cue.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { InnerTableQueryChildInformation } from "./InnerTableQueryChildInformation";
import {
  InnerTableQueryChildInformationFromJSON,
  InnerTableQueryChildInformationFromJSONTyped,
  InnerTableQueryChildInformationToJSON,
  InnerTableQueryChildInformationToJSONTyped,
} from "./InnerTableQueryChildInformation";
import type { TableQueryBaseTableEntries } from "./TableQueryBaseTableEntries";
import {
  TableQueryBaseTableEntriesFromJSON,
  TableQueryBaseTableEntriesFromJSONTyped,
  TableQueryBaseTableEntriesToJSON,
  TableQueryBaseTableEntriesToJSONTyped,
} from "./TableQueryBaseTableEntries";

/**
 *
 * @export
 * @interface TableEntriesForTreeNodesQuery
 */
export interface TableEntriesForTreeNodesQuery {
  /**
   *
   * @type {string}
   * @memberof TableEntriesForTreeNodesQuery
   */
  predicate?: string;
  /**
   *
   * @type {InnerTableQueryChildInformation}
   * @memberof TableEntriesForTreeNodesQuery
   */
  childInformation?: InnerTableQueryChildInformation;
  /**
   *
   * @type {TableQueryBaseTableEntries}
   * @memberof TableEntriesForTreeNodesQuery
   */
  tableEntries?: TableQueryBaseTableEntries;
}

/**
 * Check if a given object implements the TableEntriesForTreeNodesQuery interface.
 */
export function instanceOfTableEntriesForTreeNodesQuery(
  value: object,
): value is TableEntriesForTreeNodesQuery {
  return true;
}

export function TableEntriesForTreeNodesQueryFromJSON(
  json: any,
): TableEntriesForTreeNodesQuery {
  return TableEntriesForTreeNodesQueryFromJSONTyped(json, false);
}

export function TableEntriesForTreeNodesQueryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TableEntriesForTreeNodesQuery {
  if (json == null) {
    return json;
  }
  return {
    predicate: json["predicate"] == null ? undefined : json["predicate"],
    childInformation:
      json["childInformation"] == null
        ? undefined
        : InnerTableQueryChildInformationFromJSON(json["childInformation"]),
    tableEntries:
      json["tableEntries"] == null
        ? undefined
        : TableQueryBaseTableEntriesFromJSON(json["tableEntries"]),
  };
}

export function TableEntriesForTreeNodesQueryToJSON(
  json: any,
): TableEntriesForTreeNodesQuery {
  return TableEntriesForTreeNodesQueryToJSONTyped(json, false);
}

export function TableEntriesForTreeNodesQueryToJSONTyped(
  value?: TableEntriesForTreeNodesQuery | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    predicate: value["predicate"],
    childInformation: InnerTableQueryChildInformationToJSON(
      value["childInformation"],
    ),
    tableEntries: TableQueryBaseTableEntriesToJSON(value["tableEntries"]),
  };
}
