/* tslint:disable */
/* eslint-disable */
/**
 * Generated by cue.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { TableResponseBaseTableEntries } from "./TableResponseBaseTableEntries";
import {
  TableResponseBaseTableEntriesFromJSON,
  TableResponseBaseTableEntriesFromJSONTyped,
  TableResponseBaseTableEntriesToJSON,
  TableResponseBaseTableEntriesToJSONTyped,
} from "./TableResponseBaseTableEntries";

/**
 *
 * @export
 * @interface TableResponseBase
 */
export interface TableResponseBase {
  /**
   *
   * @type {string}
   * @memberof TableResponseBase
   */
  predicate: string;
  /**
   *
   * @type {TableResponseBaseTableEntries}
   * @memberof TableResponseBase
   */
  tableEntries: TableResponseBaseTableEntries;
  /**
   *
   * @type {Array<number>}
   * @memberof TableResponseBase
   */
  possibleRulesAbove: Array<number>;
  /**
   *
   * @type {Array<number>}
   * @memberof TableResponseBase
   */
  possibleRulesBelow: Array<number>;
}

/**
 * Check if a given object implements the TableResponseBase interface.
 */
export function instanceOfTableResponseBase(
  value: object,
): value is TableResponseBase {
  if (!("predicate" in value) || value["predicate"] === undefined) return false;
  if (!("tableEntries" in value) || value["tableEntries"] === undefined)
    return false;
  if (
    !("possibleRulesAbove" in value) ||
    value["possibleRulesAbove"] === undefined
  )
    return false;
  if (
    !("possibleRulesBelow" in value) ||
    value["possibleRulesBelow"] === undefined
  )
    return false;
  return true;
}

export function TableResponseBaseFromJSON(json: any): TableResponseBase {
  return TableResponseBaseFromJSONTyped(json, false);
}

export function TableResponseBaseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TableResponseBase {
  if (json == null) {
    return json;
  }
  return {
    predicate: json["predicate"],
    tableEntries: TableResponseBaseTableEntriesFromJSON(json["tableEntries"]),
    possibleRulesAbove: json["possibleRulesAbove"],
    possibleRulesBelow: json["possibleRulesBelow"],
  };
}

export function TableResponseBaseToJSON(json: any): TableResponseBase {
  return TableResponseBaseToJSONTyped(json, false);
}

export function TableResponseBaseToJSONTyped(
  value?: TableResponseBase | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    predicate: value["predicate"],
    tableEntries: TableResponseBaseTableEntriesToJSON(value["tableEntries"]),
    possibleRulesAbove: value["possibleRulesAbove"],
    possibleRulesBelow: value["possibleRulesBelow"],
  };
}
