// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Generated by cue.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type TableEntryQuery
 *
 * @export
 */
export type TableEntryQuery = number | string;

export function TableEntryQueryFromJSON(json: any): TableEntryQuery {
  return TableEntryQueryFromJSONTyped(json, false);
}

export function TableEntryQueryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TableEntryQuery {
  // TODO: number | string was probably not a good type for this, adjust the spec!
  return json;
}

export function TableEntryQueryToJSON(value?: TableEntryQuery | null): any {
  // TODO: number | string was probably not a good type for this, adjust the spec!
  return value;
}
