/* tslint:disable */
/* eslint-disable */
/**
 * Generated by cue.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type TableEntryQuery
 *
 * @export
 */
export type TableEntryQuery = number | string;

export function TableEntryQueryFromJSON(json: any): TableEntryQuery {
  return TableEntryQueryFromJSONTyped(json, false);
}

export function TableEntryQueryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TableEntryQuery {
  if (json == null) {
    return json;
  }
  if (instanceOfnumber(json)) {
    return numberFromJSONTyped(json, true);
  }
  if (instanceOfstring(json)) {
    return stringFromJSONTyped(json, true);
  }

  return {} as any;
}

export function TableEntryQueryToJSON(value?: TableEntryQuery | null): any {
  if (value == null) {
    return value;
  }

  if (instanceOfnumber(value)) {
    return numberToJSON(value as number);
  }
  if (instanceOfstring(value)) {
    return stringToJSON(value as string);
  }

  return {};
}
