// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Generated by cue.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { TableResponseBaseTableEntriesPagination } from "./TableResponseBaseTableEntriesPagination";
import {
  TableResponseBaseTableEntriesPaginationFromJSON,
  TableResponseBaseTableEntriesPaginationFromJSONTyped,
  TableResponseBaseTableEntriesPaginationToJSON,
  TableResponseBaseTableEntriesPaginationToJSONTyped,
} from "./TableResponseBaseTableEntriesPagination";
import type { TableEntryResponse } from "./TableEntryResponse";
import {
  TableEntryResponseFromJSON,
  TableEntryResponseFromJSONTyped,
  TableEntryResponseToJSON,
  TableEntryResponseToJSONTyped,
} from "./TableEntryResponse";

/**
 *
 * @export
 * @interface TableResponseBaseTableEntries
 */
export interface TableResponseBaseTableEntries {
  /**
   *
   * @type {Array<TableEntryResponse>}
   * @memberof TableResponseBaseTableEntries
   */
  entries: Array<TableEntryResponse>;
  /**
   *
   * @type {TableResponseBaseTableEntriesPagination}
   * @memberof TableResponseBaseTableEntries
   */
  pagination: TableResponseBaseTableEntriesPagination;
}

/**
 * Check if a given object implements the TableResponseBaseTableEntries interface.
 */
export function instanceOfTableResponseBaseTableEntries(
  value: object,
): value is TableResponseBaseTableEntries {
  if (!("entries" in value) || value["entries"] === undefined) return false;
  if (!("pagination" in value) || value["pagination"] === undefined)
    return false;
  return true;
}

export function TableResponseBaseTableEntriesFromJSON(
  json: any,
): TableResponseBaseTableEntries {
  return TableResponseBaseTableEntriesFromJSONTyped(json, false);
}

export function TableResponseBaseTableEntriesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TableResponseBaseTableEntries {
  if (json == null) {
    return json;
  }
  return {
    entries: (json["entries"] as Array<any>).map(TableEntryResponseFromJSON),
    pagination: TableResponseBaseTableEntriesPaginationFromJSON(
      json["pagination"],
    ),
  };
}

export function TableResponseBaseTableEntriesToJSON(
  json: any,
): TableResponseBaseTableEntries {
  return TableResponseBaseTableEntriesToJSONTyped(json, false);
}

export function TableResponseBaseTableEntriesToJSONTyped(
  value?: TableResponseBaseTableEntries | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    entries: (value["entries"] as Array<any>).map(TableEntryResponseToJSON),
    pagination: TableResponseBaseTableEntriesPaginationToJSON(
      value["pagination"],
    ),
  };
}
