/* tslint:disable */
/* eslint-disable */
/**
 * Generated by cue.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { TableResponseBaseTableEntries } from "./TableResponseBaseTableEntries";
import {
  TableResponseBaseTableEntriesFromJSON,
  TableResponseBaseTableEntriesFromJSONTyped,
  TableResponseBaseTableEntriesToJSON,
  TableResponseBaseTableEntriesToJSONTyped,
} from "./TableResponseBaseTableEntries";
import type { TreeForTableResponseChildInformation } from "./TreeForTableResponseChildInformation";
import {
  TreeForTableResponseChildInformationFromJSON,
  TreeForTableResponseChildInformationFromJSONTyped,
  TreeForTableResponseChildInformationToJSON,
  TreeForTableResponseChildInformationToJSONTyped,
} from "./TreeForTableResponseChildInformation";

/**
 *
 * @export
 * @interface TreeForTableResponse
 */
export interface TreeForTableResponse {
  /**
   *
   * @type {TreeForTableResponseChildInformation}
   * @memberof TreeForTableResponse
   */
  childInformation?: TreeForTableResponseChildInformation;
  /**
   *
   * @type {string}
   * @memberof TreeForTableResponse
   */
  predicate: string;
  /**
   *
   * @type {TableResponseBaseTableEntries}
   * @memberof TreeForTableResponse
   */
  tableEntries: TableResponseBaseTableEntries;
  /**
   *
   * @type {Array<number>}
   * @memberof TreeForTableResponse
   */
  possibleRulesAbove: Array<number>;
  /**
   *
   * @type {Array<number>}
   * @memberof TreeForTableResponse
   */
  possibleRulesBelow: Array<number>;
}

/**
 * Check if a given object implements the TreeForTableResponse interface.
 */
export function instanceOfTreeForTableResponse(
  value: object,
): value is TreeForTableResponse {
  if (!("predicate" in value) || value["predicate"] === undefined) return false;
  if (!("tableEntries" in value) || value["tableEntries"] === undefined)
    return false;
  if (
    !("possibleRulesAbove" in value) ||
    value["possibleRulesAbove"] === undefined
  )
    return false;
  if (
    !("possibleRulesBelow" in value) ||
    value["possibleRulesBelow"] === undefined
  )
    return false;
  return true;
}

export function TreeForTableResponseFromJSON(json: any): TreeForTableResponse {
  return TreeForTableResponseFromJSONTyped(json, false);
}

export function TreeForTableResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TreeForTableResponse {
  if (json == null) {
    return json;
  }
  return {
    childInformation:
      json["childInformation"] == null
        ? undefined
        : TreeForTableResponseChildInformationFromJSON(
            json["childInformation"],
          ),
    predicate: json["predicate"],
    tableEntries: TableResponseBaseTableEntriesFromJSON(json["tableEntries"]),
    possibleRulesAbove: json["possibleRulesAbove"],
    possibleRulesBelow: json["possibleRulesBelow"],
  };
}

export function TreeForTableResponseToJSON(json: any): TreeForTableResponse {
  return TreeForTableResponseToJSONTyped(json, false);
}

export function TreeForTableResponseToJSONTyped(
  value?: TreeForTableResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    childInformation: TreeForTableResponseChildInformationToJSON(
      value["childInformation"],
    ),
    predicate: value["predicate"],
    tableEntries: TableResponseBaseTableEntriesToJSON(value["tableEntries"]),
    possibleRulesAbove: value["possibleRulesAbove"],
    possibleRulesBelow: value["possibleRulesBelow"],
  };
}
