// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Generated by cue.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { TableQueryBaseTableEntries } from "./TableQueryBaseTableEntries";
import {
  TableQueryBaseTableEntriesFromJSON,
  TableQueryBaseTableEntriesFromJSONTyped,
  TableQueryBaseTableEntriesToJSON,
  TableQueryBaseTableEntriesToJSONTyped,
} from "./TableQueryBaseTableEntries";

/**
 *
 * @export
 * @interface TreeForTableQuery
 */
export interface TreeForTableQuery {
  /**
   *
   * @type {string}
   * @memberof TreeForTableQuery
   */
  predicate?: string;
  /**
   *
   * @type {TableQueryBaseTableEntries}
   * @memberof TreeForTableQuery
   */
  tableEntries?: TableQueryBaseTableEntries;
}

/**
 * Check if a given object implements the TreeForTableQuery interface.
 */
export function instanceOfTreeForTableQuery(
  value: object,
): value is TreeForTableQuery {
  return true;
}

export function TreeForTableQueryFromJSON(json: any): TreeForTableQuery {
  return TreeForTableQueryFromJSONTyped(json, false);
}

export function TreeForTableQueryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TreeForTableQuery {
  if (json == null) {
    return json;
  }
  return {
    predicate: json["predicate"] == null ? undefined : json["predicate"],
    tableEntries:
      json["tableEntries"] == null
        ? undefined
        : TableQueryBaseTableEntriesFromJSON(json["tableEntries"]),
  };
}

export function TreeForTableQueryToJSON(json: any): TreeForTableQuery {
  return TreeForTableQueryToJSONTyped(json, false);
}

export function TreeForTableQueryToJSONTyped(
  value?: TreeForTableQuery | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    predicate: value["predicate"],
    tableEntries: TableQueryBaseTableEntriesToJSON(value["tableEntries"]),
  };
}
